# Generated by Django 4.0.2 on 2022-09-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
